*** Variables ***

${CODE_20000}    20000
${CODE_40300}    40300
${CODE_40400}    40400
${CODE_40301}    40301
${CODE_40305}    40305
${CODE_40010}    40010
${CODE_40103}    40103
${CODE_40401}    40401

${RESULTDESC_OK}    OK
${RESULTDESC_SUCCESS}    Success
${RESULTDESC_THE_REQUESTED_OPERATION_SUCCESSFULLY}    The requested operation was successfully.
${RESULTDESC_THEIMSITHINGTOKENISNOTFOUND_ERROR}    The Imsi/ThingToken is Not Found
${RESULTDESC_FORBIDDEN_ERROR}    Forbidden
${RESULTDESC_INVALIDPAYLOAD_ERROR}    InvalidPayload
${RESULTDESC_REQUESTED_OPERATION_COULDNOTBEFOUND_ERROR}    The requested operation could not be found.
${RESULTDESC_THEOPERATIONHASALREADYEXPIRED_ERROR}    The operation has already expired.
${RESULTDESC_THETHINGIDENTIFIERREQUESTEDALREADYEXISTS_ERROR}    The ThingIdentifier requested already exists.
${RESULTDESC_REQUESTEDALREADYEXISTS_ERROR}    The requested already exists.
${RESULTDESC_DESCRIPTION_ONLINECONFIGSNOTFOUND_ERROR}    OnlineConfigs not found.
${RESULTDESC_THE_TOKEN_IS_UNTRUSTED_OR_INVALID}    The token is Untrusted or Invalid.
${RESULTDESC_THE_REQUESTED_OPERATION_HAS_BEEN_TERMINATE}    The requested operation has been terminated.